services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    devices:
      - /dev/dri:/dev/dri # For hw accelerated transcoding with a gpu
    volumes:
      - /docker_volumes/jellyfin/config:/config
      - /docker_volumes/jellyfin/cache:/cache
      - type: bind
        source: /path/to/your/media
        target: /media
        read_only: false
      # - type: bind      
      #   source: /path/to/your/music
      #   target: /music
      #   read_only: false
      # Optional - if you choose to use jellyfin as a music server as well, jellyfin needs rw access to create playlists
    restart: 'unless-stopped'
 #   environment:
#      - JELLYFIN_PublishedServerUrl=https://host.domain.tld
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
